languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseurl = "https://nekowasabi.github.io/"
canonifyurls = true
title = "lyricalie"
tags = ["tags", "categories"]
googleAnalytics = "UA-7571688-2"
copyright = "Copyright (c) 2016, takets; all rights reserved."

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
[indexes]
    category = "categories"
    tag = "tags"
[author]
    name = "takets"
    twitter = "takets"

[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
